// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs5MJZ_nunckd7k7ql2mlBzpZq2jclzy0',
    appId: '1:47971145185:web:56b2fa550a3a2b3b73eea0',
    messagingSenderId: '47971145185',
    projectId: 'wanderly-14d51',
    authDomain: 'wanderly-14d51.firebaseapp.com',
    storageBucket: 'wanderly-14d51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMnJvAnIoNVLKR4rWSbxqytD1QHyc8f9o',
    appId: '1:47971145185:android:30971b7dd5d4202c73eea0',
    messagingSenderId: '47971145185',
    projectId: 'wanderly-14d51',
    storageBucket: 'wanderly-14d51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ZKFi3-6GPUAPDQeI1kHoRM5agNZhcWM',
    appId: '1:47971145185:ios:37f0991b921a2b6073eea0',
    messagingSenderId: '47971145185',
    projectId: 'wanderly-14d51',
    storageBucket: 'wanderly-14d51.firebasestorage.app',
    iosBundleId: 'com.example.wanderly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ZKFi3-6GPUAPDQeI1kHoRM5agNZhcWM',
    appId: '1:47971145185:ios:37f0991b921a2b6073eea0',
    messagingSenderId: '47971145185',
    projectId: 'wanderly-14d51',
    storageBucket: 'wanderly-14d51.firebasestorage.app',
    iosBundleId: 'com.example.wanderly',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs5MJZ_nunckd7k7ql2mlBzpZq2jclzy0',
    appId: '1:47971145185:web:36ae41fa14e2006b73eea0',
    messagingSenderId: '47971145185',
    projectId: 'wanderly-14d51',
    authDomain: 'wanderly-14d51.firebaseapp.com',
    storageBucket: 'wanderly-14d51.firebasestorage.app',
  );

}